### ISSUE TITLE
Falscher Titel im Kalender

### ISSUE THREAD

**Issue by elangenhan** [tuiSSE/vlv.ical#106]
Nach dem Export eines Events taucht nicht der bearbeitete Name, sondern der Originale Name auf

**Comment by elangenhan** [comment]
Im bearbeitungsdialog wird der data.name geändert, im download allerdings der data.objects[i].name genommen. wie wollen wir das lösen? immer data.name benutzen, oder den namen für jedes objekt einzeln den namen änderbar machen? @nrrso

**Comment by nrrso** [comment]
data.objects[i].name soll weiterhin im Download erhalten bleiben. data.name kann evtl. noch praktisch werden für Referenzierungen, wobei wir ja origName eig haben. 
Alle Änderungen werden jetzt unter data.objects[i].XY gespeichert wie vorgesehen.
