### ISSUE TITLE
UI - Veranstaltungen

### ISSUE THREAD

**Issue by elangenhan** [tuiSSE/vlv.ical#35]
Jemand sollte sich mal darüber Gedanken machen, wie wir die einzelnen Veranstaltungen aussehen lassen wollen. Der aktuelle Stand ist soweit in Ordnung, aber ein Augenschmauß ist es auch nicht.
Es sollen alle Daten angezeigt werden, eine Möglichkeit, die Veranstaltung zum Warenkorb hinzuzufügen ist nötig und man sollte alternative Übungen auswählen können. (Nicht implementieren, erst mal nur einen UI Entwurf erstellen)

**Comment by elangenhan** [comment]
am besten sollte man sich an Norris' Design Änderungen orientieren

**Comment by nrrso** [comment]
@bayraktarberk Können uns da gerne mal zusammen dran setzen.

**Comment by bayraktarberk** [comment]
Wird erledigt Chef
