### ISSUE TITLE
(optional) Seiteninhalt bei Sidebar Öffnen

### ISSUE THREAD

**Issue by elangenhan** [tuiSSE/vlv.ical#49]
Der Content der Seite sollte bei öffnen der Sidebar zu Seite geschoben werden, damit alle Elemente auch bei geöffneter Sidebar bedient werden können.

**Comment by bayraktarberk** [comment]
Habe mich mit Norris darüber unterhalten, er meinte man kann die Hauptseite nicht mehr auswählen wenn die Sidebar offen ist. 
Würde zu viel Zeit in Anspruch nehmen, aber machbar.

**Comment by elangenhan** [comment]
Kommt auf die Displaygröße drauf an. Kann man dementsprechend abfangen und das Verhalten je nach Größe steuern.

**Comment by nrrso** [comment]
Wir müssen da nochmal schauen, wie sich das auf kleine Geräte auswirkt, da der Hauptinhalt ja nicht responsive ist.

**Comment by elangenhan** [comment]
Man kann es ja ab einer bestimmten Fenstergröße erst anwenden. Bei kleinen Geräten kann es so bleiben, wie es jetzt ist.
