### ISSUE TITLE
Zeitparsing vervollständigen

### ISSUE THREAD

**Issue by elangenhan** [tuiSSE/vlv.ical#7]
statt einer fixen Kalenderwoche und fixem Jahr soll die Funktion parseTime() richtige, vollständige Daten liefern. siehe js/helper/parseDate.js ab line 44

**Comment by nrrso** [comment]
Datum wird korrekt ausgelesen, egal ob Angabe via KW oder Datum. Es wird bis jetzt nur das letzte Datum eingetragen. 
~~TODO: Zeitspannen abdecken.~~
