### ISSUE TITLE
Local Storage name (?)

### ISSUE THREAD

**Issue by raetzer** [tuiSSE/vlv.ical#71]
Bei einem Browserneustart wird der im Local Storage hinterlegte "name:" in der Seitenleiste angezeigt und ändert sich erst nach erneutem Browserneustart wieder (insofern man ihn geändert hat)
Lässt sich schwer erklären ich versuche mich später mal dran

**Comment by elangenhan** [comment]
Wenn der Name geändert wird, soll dieser geänderte auch in der Seitenleiste auftauchen. Ist genauso gewollt, wobei wir da natürlich diskutieren können, ob wir das so machen wollen. Worauf genau willst du hinaus?
